### LOGIN
# @name login
POST {{baseUrl}}/sessions
Content-Type: application/json

{
	"email": "aluno@aluno.ufabc.edu.br",
	"password": "qwerty"
}

@token = {{login.response.body.token}}

### Refresh token
POST {{baseUrl}}/sessions/refresh
Authorization: Bearer {{token}}
