name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        work-dir: [server]
        node-version: [10.x, 12.x]
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create mongoDB docker container
        uses: DigiPie/mongo-action@v1.0.0
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        working-directory: ${{ matrix.work-dir }}
      - name: Run lint tests
        run: yarn lint
      - name: Run unit tests
        run: yarn unit_test
      - name: Run integration tests
        run: integration_test
        working-directory: ${{ matrix.work-dir }}
        env:
          NODE_ENV: drone_test
